/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.f3.calculator;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * Aplikasi kalkulator untuk melakukan perhitungan dasar.
 * 
 * --------------------------------------
 * Bebas modifikasi untuk pembelajaran.
 * 
 * @author F3
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temptResultLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        allInputLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        tujuhButton = new javax.swing.JButton();
        empatButton = new javax.swing.JButton();
        satuButton = new javax.swing.JButton();
        delapanButton = new javax.swing.JButton();
        limaButton = new javax.swing.JButton();
        duaButton = new javax.swing.JButton();
        sembilanButton = new javax.swing.JButton();
        enamButton = new javax.swing.JButton();
        tigaButton = new javax.swing.JButton();
        titikButton = new javax.swing.JButton();
        nolButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        bckspButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        bagiButton = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        AuthorLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        plusMinusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        temptResultLabel.setForeground(new java.awt.Color(255, 0, 0));
        temptResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        temptResultLabel.setName("temptResultLabel"); // NOI18N

        inputField.setEditable(false);
        inputField.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        inputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        allInputLabel.setFont(new java.awt.Font("Ubuntu", 0, 9)); // NOI18N

        resultLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultLabel.setName("resultLabel"); // NOI18N

        tujuhButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        tujuhButton.setText("7");
        tujuhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhButtonActionPerformed(evt);
            }
        });

        empatButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        empatButton.setText("4");
        empatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatButtonActionPerformed(evt);
            }
        });

        satuButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        satuButton.setText("1");
        satuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuButtonActionPerformed(evt);
            }
        });

        delapanButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        delapanButton.setText("8");
        delapanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanButtonActionPerformed(evt);
            }
        });

        limaButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        limaButton.setText("5");
        limaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaButtonActionPerformed(evt);
            }
        });

        duaButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        duaButton.setText("2");
        duaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaButtonActionPerformed(evt);
            }
        });

        sembilanButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        sembilanButton.setText("9");
        sembilanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanButtonActionPerformed(evt);
            }
        });

        enamButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        enamButton.setText("6");
        enamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamButtonActionPerformed(evt);
            }
        });

        tigaButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        tigaButton.setText("3");
        tigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaButtonActionPerformed(evt);
            }
        });

        titikButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        titikButton.setText(".");
        titikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikButtonActionPerformed(evt);
            }
        });

        nolButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        nolButton.setText("0");
        nolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        deleteButton.setText("DEL");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        bckspButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        bckspButton.setText("Bcksp");
        bckspButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckspButtonActionPerformed(evt);
            }
        });

        tambahButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        tambahButton.setText("+");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        kurangButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        kurangButton.setText("-");
        kurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangButtonActionPerformed(evt);
            }
        });

        kaliButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        kaliButton.setText("x");
        kaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliButtonActionPerformed(evt);
            }
        });

        bagiButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        bagiButton.setText("/");
        bagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiButtonActionPerformed(evt);
            }
        });

        resultButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        resultButton.setText("=");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        AuthorLabel.setFont(new java.awt.Font("Bandal", 1, 18)); // NOI18N
        AuthorLabel.setText("F3");

        jLabel5.setFont(new java.awt.Font("Bandal", 0, 11)); // NOI18N
        jLabel5.setText("Apps");

        plusMinusButton.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        plusMinusButton.setText("+/-");
        plusMinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(AuthorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(allInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tujuhButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(empatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(satuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(delapanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(limaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(duaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sembilanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tigaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(plusMinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(titikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bckspButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(resultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(temptResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AuthorLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temptResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delapanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duaButton)
                            .addComponent(tigaButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sembilanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enamButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tujuhButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titikButton)
                            .addComponent(nolButton)
                            .addComponent(plusMinusButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bckspButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton)
                            .addComponent(kaliButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bagiButton)
                            .addComponent(resultButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kurangButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tujuhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhButtonActionPerformed
        printButton("7");
    }//GEN-LAST:event_tujuhButtonActionPerformed

    private void delapanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanButtonActionPerformed
        printButton("8");
    }//GEN-LAST:event_delapanButtonActionPerformed

    private void sembilanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanButtonActionPerformed
        printButton("9");
    }//GEN-LAST:event_sembilanButtonActionPerformed

    private void empatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatButtonActionPerformed
        printButton("4");
    }//GEN-LAST:event_empatButtonActionPerformed

    private void limaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaButtonActionPerformed
        printButton("5");
    }//GEN-LAST:event_limaButtonActionPerformed

    private void enamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamButtonActionPerformed
        printButton("6");
    }//GEN-LAST:event_enamButtonActionPerformed

    private void satuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuButtonActionPerformed
        printButton("1");
    }//GEN-LAST:event_satuButtonActionPerformed

    private void duaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaButtonActionPerformed
        printButton("2");
    }//GEN-LAST:event_duaButtonActionPerformed

    private void tigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaButtonActionPerformed
        printButton("3");
    }//GEN-LAST:event_tigaButtonActionPerformed

    private void titikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikButtonActionPerformed
        printButton(".");
    }//GEN-LAST:event_titikButtonActionPerformed

    private void nolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolButtonActionPerformed
        printButton("0");
    }//GEN-LAST:event_nolButtonActionPerformed

    /**
     * Hapus input jTextField satu persatu.
     * @param evt 
     */
    private void bckspButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckspButtonActionPerformed
        if(done)
            clear();
        else{
            String inputFieldText = inputField.getText();
            
            if(!inputFieldText.equals("")){ // string dari inputfield harus di bandingkan dengan method equals
                StringBuilder textTextField = new StringBuilder(inputFieldText);
                StringBuilder textLabel1 = new StringBuilder(allInputLabel.getText());

                textTextField.deleteCharAt(textTextField.length() - 1); // hapus satu karakter paling belakang
                textLabel1.deleteCharAt(textLabel1.length() - 1); // hapus satu karakter paling belakang

                inputField.setText(textTextField.toString());
                allInputLabel.setText(textLabel1.toString());
            }
        }
    }//GEN-LAST:event_bckspButtonActionPerformed

    /**
     * Hapus input jTextField keseluruhan.
     * dan hapus string label sebanyak input jTextField yang dihapus
     * @param evt 
     */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(done)
            clear();
        else{
            String inputFieldText = inputField.getText();
            int jTextFieldLength = inputFieldText.length();
            
            if(!inputFieldText.equals("")){ // string dari inputfield harus di bandingkan dengan method equals
                inputField.setText("");
                
                StringBuilder label1Text = new StringBuilder(allInputLabel.getText());
                int textLabelLength = label1Text.length();
                
                label1Text.delete((textLabelLength - jTextFieldLength), textLabelLength); // hapus string label sebanyak input jTextField yang dihapus
                allInputLabel.setText(label1Text.toString());
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        storeInput('+');
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        storeInput('-');
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        storeInput('x');
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        storeInput('/');
    }//GEN-LAST:event_bagiButtonActionPerformed

    /**
     * Lakukan perhitungan dan tampilkan hasil.
     * @param evt 
     */
    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        if(!done){
            if(!inputField.getText().equals("")){
                try{
                    
                    doCalculation();
                    printResult(resultLabel);
                    
                }catch(NumberFormatException ex){
                    
                    JOptionPane.showMessageDialog(this,
                            "Illegal Notation",
                            "Error",
                            JOptionPane.WARNING_MESSAGE);
                    clear();
                    
                }catch(Exception ex){
                    
                    clear();
                }
            }
            
            done = true;
        }
    }//GEN-LAST:event_resultButtonActionPerformed

    private void plusMinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusMinusButtonActionPerformed
        printButton("-");
    }//GEN-LAST:event_plusMinusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException |
                InstantiationException |
                IllegalAccessException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }
    
    /**
     * Tampilkan hasil.
     * @param jlabel 
     */
    private void printResult(JLabel jlabel){
        double tempt = lastResult;
        String labelName = jlabel.getName();
        
        if(lastResult < 0) // cek dahulu apakah lastresult minus / kurang dari 0
            tempt = Math.abs(lastResult); // positifkan hasil lastresult dan simpan ke variable sementara
            
        if((tempt % 1) > 0){ // jika lastresult yang di positifkan lebih besar dari nol (alias pecahan desimal di belakang komanya bukan nol), maka tampilkan lastresult yang asli apa adanya (tanpa format)
                if(labelName.equals("resultLabel"))
                    resultLabel.setText("= " + lastResult);
                else if(labelName.equals("temptResultLabel"))
                    temptResultLabel.setText("" + lastResult + operator);
                
        } else if((tempt % 1) == 0){ // sebaliknya jika lastresult yang di positifkan sama dengan nol (alias pecahan desimal di belakang komanya adalah nol (hasil default perhitungan tipe data double)),
            String slr = String.format("%.0f", lastResult); // maka format dan tampilkan lastresult yang asli (tanpa menampilkan pecahan desimal nol di belakang koma)

            if(labelName.equals("resultLabel"))
                resultLabel.setText("= " + slr);
            else if(labelName.equals("temptResultLabel"))
                temptResultLabel.setText(slr + operator);
        }
    }
    
    /**
     * Simpan input dan lakukan perhitungan sementara
     * @param operator 
     */
    private void storeInput(char operator){
        if(!done){
            String inputFieldText = inputField.getText();

            if(!inputFieldText.equals("")){
                allInputLabel.setText(allInputLabel.getText() + operator);

                try{
                    if(temptResultLabel.getText().equals("")){ // jika true, tampilkan ke label tanpa perhitunngan terlebih dahulu
                        this.operator = operator;

                        lastResult = Double.parseDouble(inputFieldText);
                        temptResultLabel.setText(inputFieldText + operator);
                    } else{ // sebaliknya, langsung lakukang perhitungan dan tampilkan hasil ke label
                        doCalculation(); // lakukan perhitungan terlebih dahulu
                        this.operator = operator; // baru simpan operator selanjutnya
                        
                        printResult(temptResultLabel);
                    }

                    inputField.setText("");
                }catch(NumberFormatException ex){
                    
                    JOptionPane.showMessageDialog(this,
                            "Illegal Notation",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    
                    clear();
                    
                }catch(Exception ex){
                    
                    clear();
                }
            } else if(inputFieldText.equals("") && !temptResultLabel.getText().equals("")) // jika true berarti mengganti operator
                changeOperator(operator);
        }
    }
    
    /**
     * Lakukan perhitungan.
     * @throws NumberFormatException 
     */
    private void doCalculation() throws NumberFormatException{
        double bil = Double.parseDouble(inputField.getText());
        
        switch(operator){
            case '+':
                lastResult += bil;
                break;
            case '-':
                lastResult -= bil;
                break;
            case 'x':
                lastResult *= bil;
                break;
            case '/':
                lastResult /= bil;
                break;
        }
    }
    
    /**
     * Tampilkan setiap input ke jTextField dan jLabel.
     * @param num 
     */
    private void printButton(String num){
        if(done)
            clear();
        
        inputField.setText(inputField.getText() + num);
        allInputLabel.setText(allInputLabel.getText() + num);
        
        done = false;
    }
    
    /**
     * Ganti operator.
     * @param op 
     */
    private void changeOperator(char op){
        operator = op;
        
        StringBuilder label1Text = new StringBuilder(allInputLabel.getText());
        StringBuilder label2Text = new StringBuilder(temptResultLabel.getText());
        
        label1Text.setCharAt(label1Text.length() - 1, op); // hapus karakter di string paling belakang (string operator) dan ganti dengan karakter (operator) baru
        label2Text.setCharAt(label2Text.length() - 1, op);
        
        allInputLabel.setText(label1Text.toString());
        temptResultLabel.setText(label2Text.toString());
    }
    
    /**
     * Bersihkan output.
     */
    private void clear(){
        allInputLabel.setText("");
        temptResultLabel.setText("");
        resultLabel.setText("");
        inputField.setText("");
    }
    
    
    
    /* Property dan Variable tambahan */
    private double lastResult;
    private char operator;
    private static boolean done = false; // untuk cek apakah perhitungan sudah di lakukan
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorLabel;
    private javax.swing.JLabel allInputLabel;
    private javax.swing.JButton bagiButton;
    private javax.swing.JButton bckspButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton delapanButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton duaButton;
    private javax.swing.JButton empatButton;
    private javax.swing.JButton enamButton;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kaliButton;
    private javax.swing.JButton kurangButton;
    private javax.swing.JButton limaButton;
    private javax.swing.JButton nolButton;
    private javax.swing.JButton plusMinusButton;
    private javax.swing.JButton resultButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton satuButton;
    private javax.swing.JButton sembilanButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JLabel temptResultLabel;
    private javax.swing.JButton tigaButton;
    private javax.swing.JButton titikButton;
    private javax.swing.JButton tujuhButton;
    // End of variables declaration//GEN-END:variables
}
